apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-video-to-gif
  namespace: video-to-gif
spec:
  acme:
    # Let's Encrypt ACME 서버 URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # 인증서 관련 알림을 받을 이메일 주소 (변경 필요)
    email: dev.shinkeonkim@gmail.com
    privateKeySecretRef:
      # ACME 계정 프라이빗 키가 저장될 시크릿 이름
      name: lletsencrypt-prod-video-to-gif
    # HTTP-01 챌린지 방식 사용
    solvers:
    - http01:
        ingress:
          class: nginx
